name: Build and Publish to NPM

on:
  # Runs on pushes tags
  push:
    tags:
      - v0.*
      - v1.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Publish
        uses: actions/setup-node@v3
      - run: |
          node -v
          npm -v
          npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
