name: Build and Publish to NPM

on:
  # release:
  #   types: [created]
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

  # Runs on pushes tags
  push:
    tags:
      - v0.*
      - v1.*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm install && npm run build
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
