name: Deploy static content to Pages

on:
  # Runs on pushes tags
  push:
    tags:
      - v0.*
      - v1.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
      - run: |
          node -v
          npm -v

      - name: Build
      - run: |
          npm install
          npm run build

      - name: Publish package on NPM📦
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}