name: Build and Publish to NPM

on:
  # release:
  #   types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs on pushes tags
  push:
    tags:
      - v0.*
      - v1.*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
